In [24]:
from pyinaturalist import *
import pandas as pd




ambystoma = 26721 # taxon id (Ambystoma genus)
states = { # place ids
    "OH": 31,
    "MI": 29,
    "IN": 20,
    "PA": 42,
    "KY": 26,
    "WV": 33
}


observations = {"results": [], "total_results": 0}
for state in states:
    response = get_observations(
        taxon_id=ambystoma,
        place_id=states[state],
        quality_grade='research',
        captive=False,   # exclude captive/zoo observations
        page="all",      # fetch all pages
    )
    for obs in response['results']:
        obs['state'] = state  # tag each record with its state
    observations['results'].extend(response['results'])
    observations['total_results'] += response['total_results']
    print(f"{state}: {response['total_results']} research-grade Ambystoma observations")

print(f"Total: {observations['total_results']} research-grade Ambystoma observations across {len(states)} states")
pprint(observations['results'][:5])

OH: 3844 research-grade Ambystoma observations
MI: 3042 research-grade Ambystoma observations
IN: 2723 research-grade Ambystoma observations
PA: 2234 research-grade Ambystoma observations
KY: 1462 research-grade Ambystoma observations
WV: 490 research-grade Ambystoma observations
Total: 13795 research-grade Ambystoma observations across 6 states

  ID      Taxon ID   Taxon                             Observed on    User         Location
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  36089   26736      Ambystoma opacum (Marbled         Jul 15, 2010   brianslaby   Wayne National Forest, OH
                     Salamander)
  36093   26790      Ambystoma maculatum (Spotted      Mar 19, 2008   brianslaby   Taylor-Ochs Pond, Denison
                     Salamander)                                                   University Biological Reserve
  36102   26790      Ambystoma maculatum (Spotted      Mar 27, 2008   brianslaby   Taylor-Ochs Pond, Denison
                     Salamander)                                                   University Biological Reserve
  38447   26749      Ambystoma tigrinum (Eastern       Sep 05, 2011   matts21      Ohio, US
                     Tiger Salamander)
  56232   26752      Ambystoma barbouri (Streamside    Mar 04, 2012   chia         United States
                     Salamander)

In [25]:
df = pd.DataFrame(observations['results'])
df.head()

,quality_grade,taxon_geoprivacy,annotations,uuid,observed_on_details,id,cached_votes_total,identifications_most_agree,created_at_details,species_guess,...,identifications_some_agree,project_ids_without_curator_id,place_guess,identifications,project_observations,observation_photos,photos,faves,non_owner_ids,state
0,research,open,[],dc5b911a-71d9-4d99-bbcb-af82f7883873,"{'date': '2010-07-15', 'day': 15, 'month': 7, ...",36089,0,True,"{'date': '2011-10-19', 'day': 19, 'month': 10,...",Marbled Salamander,...,True,"[13, 79]","Wayne National Forest, OH","[{'id': 45005, 'uuid': 'c2bd4b1d-2622-4021-869...","[{'id': 9733, 'uuid': 'b5c2c24d-89e8-4b44-aea5...","[{'id': 43161, 'position': 0, 'uuid': '09009ac...","[{'id': 61003, 'license_code': None, 'original...",[],"[{'id': 45029, 'uuid': '1dafc61d-478a-4601-949...",OH
1,research,open,[],51bad00c-20ed-4613-b72c-c39ab540f095,"{'date': '2008-03-19', 'day': 19, 'month': 3, ...",36093,0,True,"{'date': '2011-10-19', 'day': 19, 'month': 10,...",Spotted Salamander,...,True,"[79, 174]","Taylor-Ochs Pond, Denison University Biologica...","[{'id': 45011, 'uuid': 'a5611ae8-4996-4fa3-ba3...","[{'id': 7965, 'uuid': '44b329a4-86a0-45e3-b313...","[{'id': 43165, 'position': 0, 'uuid': 'ff5040d...","[{'id': 61007, 'license_code': None, 'original...",[],"[{'id': 45145, 'uuid': '4257ddff-3db7-4773-999...",OH
2,research,open,[],d50bc488-202c-4310-a1f4-a4a094f0f2a7,"{'date': '2008-03-27', 'day': 27, 'month': 3, ...",36102,5,True,"{'date': '2011-10-19', 'day': 19, 'month': 10,...",Spotted Salamander,...,True,"[79, 174, 4641, 123770]","Taylor-Ochs Pond, Denison University Biologica...","[{'id': 45026, 'uuid': '5e1f15f1-7a22-4acd-a38...","[{'id': 9732, 'uuid': '192b3097-7221-4cea-865e...","[{'id': 43174, 'position': 0, 'uuid': 'bd0e42a...","[{'id': 61016, 'license_code': None, 'original...","[{'id': 3568192, 'vote_flag': True, 'vote_scop...","[{'id': 45027, 'uuid': 'cdaa7f41-9843-49fc-9bb...",OH
3,research,obscured,[],e86428fe-2c1c-498c-ba56-bee0227cd123,"{'date': '2011-09-05', 'day': 5, 'month': 9, '...",38447,0,True,"{'date': '2011-11-07', 'day': 7, 'month': 11, ...",Eastern Tiger Salamander,...,True,"[13, 79, 174, 4641]","Ohio, US","[{'id': 49415, 'uuid': 'a921693d-c89f-40e6-bab...","[{'id': 10998, 'uuid': 'b57a0cfc-d218-4558-84f...","[{'id': 45948, 'position': 0, 'uuid': 'a13ee08...","[{'id': 64073, 'license_code': None, 'original...",[],"[{'id': 49464, 'uuid': '27a403db-ce9a-4fdc-adc...",OH
4,research,open,[],0763bd8d-7f50-4f48-bd3a-68f45da0faf8,"{'date': '2012-03-04', 'day': 4, 'month': 3, '...",56232,0,True,"{'date': '2012-03-08', 'day': 8, 'month': 3, '...",Streamside Salamander,...,True,"[79, 13, 2218, 47234]",United States,"[{'id': 79910, 'uuid': '6ebf0231-d6ce-4cdf-86a...","[{'id': 16638, 'uuid': '3aaaafe5-f252-4f64-a47...","[{'id': 2506194, 'position': 0, 'uuid': '63ddb...","[{'id': 2646111, 'license_code': 'cc-by-nc', '...",[],"[{'id': 79971, 'uuid': '1a9fa3bf-8bba-4a3a-853...",OH

In [ ]:
df['species'] = df['taxon'].apply(lambda t: t['name'])

0       Ambystoma opacum
1    Ambystoma maculatum
2    Ambystoma maculatum
3     Ambystoma tigrinum
4     Ambystoma barbouri
Name: species, dtype: object

In [46]:
df.head()

,quality_grade,taxon_geoprivacy,annotations,uuid,observed_on_details,id,cached_votes_total,identifications_most_agree,created_at_details,species_guess,...,project_ids_without_curator_id,place_guess,identifications,project_observations,observation_photos,photos,faves,non_owner_ids,state,species
0,research,open,[],dc5b911a-71d9-4d99-bbcb-af82f7883873,"{'date': '2010-07-15', 'day': 15, 'month': 7, ...",36089,0,True,"{'date': '2011-10-19', 'day': 19, 'month': 10,...",Marbled Salamander,...,"[13, 79]","Wayne National Forest, OH","[{'id': 45005, 'uuid': 'c2bd4b1d-2622-4021-869...","[{'id': 9733, 'uuid': 'b5c2c24d-89e8-4b44-aea5...","[{'id': 43161, 'position': 0, 'uuid': '09009ac...","[{'id': 61003, 'license_code': None, 'original...",[],"[{'id': 45029, 'uuid': '1dafc61d-478a-4601-949...",OH,Ambystoma opacum
1,research,open,[],51bad00c-20ed-4613-b72c-c39ab540f095,"{'date': '2008-03-19', 'day': 19, 'month': 3, ...",36093,0,True,"{'date': '2011-10-19', 'day': 19, 'month': 10,...",Spotted Salamander,...,"[79, 174]","Taylor-Ochs Pond, Denison University Biologica...","[{'id': 45011, 'uuid': 'a5611ae8-4996-4fa3-ba3...","[{'id': 7965, 'uuid': '44b329a4-86a0-45e3-b313...","[{'id': 43165, 'position': 0, 'uuid': 'ff5040d...","[{'id': 61007, 'license_code': None, 'original...",[],"[{'id': 45145, 'uuid': '4257ddff-3db7-4773-999...",OH,Ambystoma maculatum
2,research,open,[],d50bc488-202c-4310-a1f4-a4a094f0f2a7,"{'date': '2008-03-27', 'day': 27, 'month': 3, ...",36102,5,True,"{'date': '2011-10-19', 'day': 19, 'month': 10,...",Spotted Salamander,...,"[79, 174, 4641, 123770]","Taylor-Ochs Pond, Denison University Biologica...","[{'id': 45026, 'uuid': '5e1f15f1-7a22-4acd-a38...","[{'id': 9732, 'uuid': '192b3097-7221-4cea-865e...","[{'id': 43174, 'position': 0, 'uuid': 'bd0e42a...","[{'id': 61016, 'license_code': None, 'original...","[{'id': 3568192, 'vote_flag': True, 'vote_scop...","[{'id': 45027, 'uuid': 'cdaa7f41-9843-49fc-9bb...",OH,Ambystoma maculatum
3,research,obscured,[],e86428fe-2c1c-498c-ba56-bee0227cd123,"{'date': '2011-09-05', 'day': 5, 'month': 9, '...",38447,0,True,"{'date': '2011-11-07', 'day': 7, 'month': 11, ...",Eastern Tiger Salamander,...,"[13, 79, 174, 4641]","Ohio, US","[{'id': 49415, 'uuid': 'a921693d-c89f-40e6-bab...","[{'id': 10998, 'uuid': 'b57a0cfc-d218-4558-84f...","[{'id': 45948, 'position': 0, 'uuid': 'a13ee08...","[{'id': 64073, 'license_code': None, 'original...",[],"[{'id': 49464, 'uuid': '27a403db-ce9a-4fdc-adc...",OH,Ambystoma tigrinum
4,research,open,[],0763bd8d-7f50-4f48-bd3a-68f45da0faf8,"{'date': '2012-03-04', 'day': 4, 'month': 3, '...",56232,0,True,"{'date': '2012-03-08', 'day': 8, 'month': 3, '...",Streamside Salamander,...,"[79, 13, 2218, 47234]",United States,"[{'id': 79910, 'uuid': '6ebf0231-d6ce-4cdf-86a...","[{'id': 16638, 'uuid': '3aaaafe5-f252-4f64-a47...","[{'id': 2506194, 'position': 0, 'uuid': '63ddb...","[{'id': 2646111, 'license_code': 'cc-by-nc', '...",[],"[{'id': 79971, 'uuid': '1a9fa3bf-8bba-4a3a-853...",OH,Ambystoma barbouri